services:
  spark:
    image: jupyter/pyspark-notebook
    ports:
      - "8888:8888"
      - "4040:4040"
    environment:
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON_OPTS='notebook --ip=0.0.0.0 --no-browser --allow-root'
    volumes:
      - ./data:/home/jovyan/work/data
      - ./docs:/home/jovyan/work/docs
      - ./notebooks:/home/jovyan/work/notebooks